http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: "localhost"
    paths: /api/v1/*
    methods: ["GET", "POST"]
serviceEndpoints:
  api-service:
    url: "http://localhost:8000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: api-service
